name: Build tvOS Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Locate Xcode project
        id: locate_xcode_project
        run: |
          if [ -f "./*.xcworkspace" ]; then
            echo "workspace=$(find . -name '*.xcworkspace')" >> $GITHUB_ENV
            echo "scheme=$(xcodebuild -list -json | jq -r '.workspace.schemes[0]')" >> $GITHUB_ENV
          elif [ -f "./*.xcodeproj" ]; then
            echo "project=$(find . -name '*.xcodeproj')" >> $GITHUB_ENV
            echo "scheme=$(xcodebuild -list -json | jq -r '.project.schemes[0]')" >> $GITHUB_ENV
          fi
          
      - name: Build Application
        run: |
          if [ -n "$workspace" ]; then
            xcodebuild -workspace "$workspace" -scheme "$scheme" -sdk appletvos -configuration Release archive -archivePath $PWD/build/tvOS.xcarchive
          elif [ -n "$project" ]; then
            xcodebuild -project "$project" -scheme "$scheme" -sdk appletvos -configuration Release archive -archivePath $PWD/build/tvOS.xcarchive
          fi

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/tvOS.xcarchive -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string></string>
            </dict>
            </plist>') -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: tvOS-App
          path: build/*.ipa
