name: Build tvOS Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install CocoaPods
        run: |
          gem install cocoapods 2>&1 | tee -a build.log
          pod install 2>&1 | tee -a build.log

      - name: Locate Xcode project
        id: locate_xcode_project
        run: |
          if [ -f "./*.xcworkspace" ]; then
            echo "workspace=$(find . -name '*.xcworkspace')" >> $GITHUB_ENV
            echo "scheme=$(xcodebuild -list -json | jq -r '.workspace.schemes[0]')" >> $GITHUB_ENV
          elif [ -f "./*.xcodeproj" ]; then
            echo "project=$(find . -name '*.xcodeproj')" >> $GITHUB_ENV
            echo "scheme=$(xcodebuild -list -json | jq -r '.project.schemes[0]')" >> $GITHUB_ENV
          fi

      - name: Build Application
        run: |
          if [ -n "$workspace" ]; then
            xcodebuild -workspace "$workspace" -scheme "$scheme" -sdk appletvos -configuration Release archive -archivePath $PWD/build/tvOS.xcarchive 2>&1 | tee -a build.log
          elif [ -n "$project" ]; then
            xcodebuild -project "$project" -scheme "$scheme" -sdk appletvos -configuration Release archive -archivePath $PWD/build/tvOS.xcarchive 2>&1 | tee -a build.log

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/tvOS.xcarchive -exportOptionsPlist $PWD/UpcomingMovies/Info.plist -exportPath $PWD/build 2>&1 | tee -a build.log

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: tvOS-App
          path: build/*.ipa
